[project]
name = "megashtein"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "optuna>=4.4.0",
    "pymupdf>=1.26.3",
    "pypdf2>=3.0.1",
    "rapidfuzz>=3.12.2",
    "torch>=2.6.0",
]
