[project]
name = "megashtein"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rapidfuzz>=3.12.2",
    "torch>=2.6.0",
]
